language: php
php:      [ "5.4" ]
env:      [ "WD_BROWSER=firefox", "WD_BROWSER=chrome" ]
script:   "./test.sh"

# Inspired from http://knpuniversity.com/screencast/question-answer-day/travis-ci
before_script:
    - sudo apt-get update -qq

    # Apache
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-imagick
    - sudo sed -i -e "s,/var/www,$(pwd)/website,g" /etc/apache2/sites-available/default
    - sudo sed -i -e "s,AllowOverride None,AllowOverride All,g" /etc/apache2/sites-available/default
    - cat /etc/apache2/envvars
    - sudo sed -i -e "s,www-data,$(whoami),g" /etc/apache2/envvars
    - sudo a2enmod php5
    - sudo /etc/init.d/apache2 stop
    - sudo rm -rf /var/lock/apache2
    - sudo /etc/init.d/apache2 start

    # XVFB
    - "export DISPLAY=:99.0"
    - "Xvfb :99.0 -extension RANDR > /dev/null &"

    # Selenium server
    - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
    - "java -jar selenium-server-standalone-2.39.0.jar > /dev/null 2>/dev/null &"

    # Browser
    - './.travis-browser.sh $WD_BROWSER'
